"""empty message

Revision ID: 08547f95cb72
Revises: 589d8119e6d0
Create Date: 2022-11-29 10:20:05.242016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08547f95cb72'
down_revision = '589d8119e6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
